name: Bowlingline
options:
  bundleIdPrefix: com.shimondeitel.bowlspend
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Bowlingline:
    type: application
    platform: iOS
    sources:
      - path: Bowlingline
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bowlspend
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Bowlingline/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  BowlinglineTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BowlinglineTests
      - path: Bowlingline.storekit
    dependencies:
      - target: Bowlingline
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bowlspend.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  BowlinglineUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BowlinglineUITests
    dependencies:
      - target: Bowlingline
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bowlspend.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Bowlingline:
    build:
      targets:
        Bowlingline: all
        BowlinglineTests: [test]
        BowlinglineUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Bowlingline.storekit
    test:
      config: Debug
      storeKitConfiguration: Bowlingline.storekit
      targets:
        - BowlinglineTests
        - BowlinglineUITests
    archive:
      config: Release
